/**
 * Employee → My Payroll / Payslips
 * Shows the Financial Year filter and payslip table — identical to the
 * original Payslips tab on the Home → Overview page.
 */
import React, { useEffect, useState } from 'react';
import { FileText, Filter } from 'lucide-react';
import api from '../../utils/api';

/* Compute the current FY string, e.g. "2026-27" */
function currentFY() {
  const now = new Date();
  const m = now.getMonth() + 1;
  const y = now.getFullYear();
  return m >= 4 ? `${y}-${String(y + 1).slice(2)}` : `${y - 1}-${String(y).slice(2)}`;
}

/* Generate current FY and previous two FYs dynamically, e.g. ["2024-25", "2025-26", "2026-27"] */
function getFYList() {
  const now = new Date();
  const m = now.getMonth() + 1;
  const y = now.getFullYear();
  const currentStart = m >= 4 ? y : y - 1;

  const list = [];
  for (let i = 2; i >= 0; i--) {
    const start = currentStart - i;
    const end = start + 1;
    list.push(`${start}-${String(end).slice(2)}`);
  }
  return list;
}

const fmtINR = (n) =>
  n != null
    ? `₹${Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    : '—';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function MyPayroll() {
  const [payslips, setPayslips] = useState([]);
  const [payslipFY, setPayslipFY] = useState(currentFY);
  const [loading, setLoading] = useState(false);

  const fyList = getFYList();

  useEffect(() => {
    setLoading(true);
    api.get('/payslips?fy=' + payslipFY)
      .then((p) => {
        setPayslips(p.data.data || []);
      })
      .catch(() => { })
      .finally(() => setLoading(false));
  }, [payslipFY]);

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-5">
      {/* Header */}
      <div>
        <h1 className="text-[20px] font-bold text-slate-800">My Payroll</h1>
        <p className="text-[13px] text-slate-500 mt-1">
          Your monthly payslips filtered by Financial Year.
        </p>
      </div>

      {/* Financial Year Filter + Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        {/* FY filter bar */}
        <div className="px-5 py-3.5 border-b border-slate-100 flex items-center gap-3">
          <Filter size={14} className="text-[#1a73e8]" />
          <span className="text-[13px] font-semibold text-slate-700">Financial Year :</span>
          <select
            value={payslipFY}
            onChange={e => setPayslipFY(e.target.value)}
            className="border border-slate-200 rounded px-2 py-1 text-[12.5px] font-bold text-[#1a73e8] outline-none focus:border-blue-300 bg-white"
          >
            {(fyList.length > 0 ? fyList : [payslipFY]).map(fy => (
              <option key={fy} value={fy}>Financial Year : {fy.replace('-', '–')}</option>
            ))}
          </select>
        </div>

        {/* Body */}
        {loading ? (
          <div className="flex justify-center py-12">
            <div className="w-6 h-6 border-[3px] border-[#1a73e8] border-t-transparent rounded-full animate-spin" />
          </div>
        ) : payslips.length === 0 ? (
          <div className="p-14 text-center">
            <FileText size={28} className="text-slate-200 mx-auto mb-3" />
            <p className="text-[13px] font-semibold text-slate-500">
              No payslips found for FY {payslipFY.replace('-', '–')}
            </p>
            <p className="text-[12px] text-slate-400 mt-1">Payslips will appear once generated by HR.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-slate-100">
                  {['Month', 'Gross Pay', 'Reimbursements', 'Deductions', 'Take Home', 'Payslips', 'Tax Worksheet'].map(h => (
                    <th
                      key={h}
                      className="px-5 py-3 text-left text-[11.5px] font-semibold text-slate-500 uppercase tracking-wider"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {payslips.map(p => (
                  <tr key={p._id} className="hover:bg-slate-50 transition-colors">
                    <td className="px-5 py-3.5">
                      <span className="text-[13px] font-semibold text-[#1a73e8]">
                        {MONTHS[(p.month || 1) - 1]} {p.year}
                      </span>
                    </td>
                    <td className="px-5 py-3.5 text-[13px] text-slate-700">{fmtINR(p.grossPay)}</td>
                    <td className="px-5 py-3.5 text-[13px] text-slate-700">{fmtINR(p.reimbursements)}</td>
                    <td className="px-5 py-3.5 text-[13px] text-slate-700">{fmtINR(p.deductions)}</td>
                    <td className="px-5 py-3.5 text-[13.5px] font-bold text-slate-800">{fmtINR(p.takeHome)}</td>
                    <td className="px-5 py-3.5">
                      {p.payslipUrl
                        ? <a href={p.payslipUrl} target="_blank" rel="noreferrer" className="text-[13px] font-semibold text-[#1a73e8] hover:underline">View</a>
                        : <span className="text-[12.5px] text-slate-400">—</span>}
                    </td>
                    <td className="px-5 py-3.5">
                      {p.taxWorksheetUrl
                        ? <a href={p.taxWorksheetUrl} target="_blank" rel="noreferrer" className="text-[13px] font-semibold text-[#1a73e8] hover:underline">View</a>
                        : <span className="text-[12.5px] text-slate-400">—</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
