param(
    [string]$PgPassword = ""
)

# ============================================================
# Nxt People - PostgreSQL Database Setup Script
# ============================================================

$PG_BIN  = "C:\Program Files\PostgreSQL\17\bin"
$PG_USER = "postgres"
$PG_HOST = "localhost"
$PG_PORT = "5432"
$DB_NAME = "nxt_people"
$psql    = "$PG_BIN\psql.exe"

$backendDir = Join-Path $PSScriptRoot "backend"

# ---- Get password ----
if ($PgPassword -eq "") {
    $secure = Read-Host "Enter PostgreSQL 'postgres' password" -AsSecureString
    $PgPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
}

$env:PGPASSWORD = $PgPassword

# ---- Test connection ----
Write-Host "" 
Write-Host "Testing PostgreSQL connection..." -ForegroundColor Cyan
$result = & $psql -U $PG_USER -h $PG_HOST -p $PG_PORT postgres -c "SELECT 1;" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAILED: Cannot connect to PostgreSQL." -ForegroundColor Red
    Write-Host $result
    exit 1
}
Write-Host "Connected successfully!" -ForegroundColor Green

# ---- Create database ----
Write-Host ""
Write-Host "Creating database '$DB_NAME'..." -ForegroundColor Cyan
$dbExists = & $psql -U $PG_USER -h $PG_HOST -p $PG_PORT postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME';"
if ($dbExists -eq "1") {
    Write-Host "Database '$DB_NAME' already exists - skipping creation." -ForegroundColor Yellow
} else {
    & $psql -U $PG_USER -h $PG_HOST -p $PG_PORT postgres -c "CREATE DATABASE $DB_NAME;"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAILED: Could not create database." -ForegroundColor Red
        exit 1
    }
    Write-Host "Database '$DB_NAME' created!" -ForegroundColor Green
}

# ---- Write .env file ----
Write-Host ""
Write-Host "Writing .env file..." -ForegroundColor Cyan

$jwtSecret = [System.Guid]::NewGuid().ToString("N") + [System.Guid]::NewGuid().ToString("N")

$envContent = "# Auto-generated by setup_database.ps1`r`n"
$envContent += "`r`n# Server`r`n"
$envContent += "PORT=5000`r`n"
$envContent += "NODE_ENV=development`r`n"
$envContent += "CORS_ORIGIN=http://localhost:5173`r`n"
$envContent += "FRONTEND_URL=http://localhost:5173`r`n"
$envContent += "COMPANY_NAME=Nxt People`r`n"
$envContent += "ADMIN_EMAIL=admin@nxtpeople.com`r`n"
$envContent += "`r`n# Database (PostgreSQL)`r`n"
$envContent += "DB_HOST=$PG_HOST`r`n"
$envContent += "DB_PORT=$PG_PORT`r`n"
$envContent += "DB_USER=$PG_USER`r`n"
$envContent += "DB_PASSWORD=$PgPassword`r`n"
$envContent += "DB_NAME=$DB_NAME`r`n"
$envContent += "`r`n# Auth / JWT`r`n"
$envContent += "JWT_SECRET=$jwtSecret`r`n"
$envContent += "JWT_ACCESS_EXPIRE=15m`r`n"
$envContent += "JWT_EXPIRE=7d`r`n"
$envContent += "`r`n# SMTP (optional - leave blank to skip email)`r`n"
$envContent += "EMAIL_SERVICE=gmail`r`n"
$envContent += "EMAIL_HOST=smtp.gmail.com`r`n"
$envContent += "EMAIL_PORT=587`r`n"
$envContent += "EMAIL_USER=`r`n"
$envContent += "EMAIL_PASS=`r`n"
$envContent += "`r`n# Optional integrations`r`n"
$envContent += "ZOHO_CLIENT_ID=`r`n"
$envContent += "ZOHO_CLIENT_SECRET=`r`n"
$envContent += "ZOHO_REFRESH_TOKEN=`r`n"
$envContent += "ZOHO_API_DOMAIN=https://people.zoho.in`r`n"
$envContent += "ZOHO_AUTH_URL=https://accounts.zoho.in/oauth/v2/token`r`n"
$envContent += "SENTRY_DSN_BACKEND=`r`n"
$envContent += "SENTRY_ENVIRONMENT=development`r`n"
$envContent += "SENTRY_TRACES_SAMPLE_RATE=0.1`r`n"
$envContent += "LOG_LEVEL=debug`r`n"
$envContent += "RATE_LIMIT_DISABLED=`r`n"

$envPath = Join-Path $backendDir ".env"
[System.IO.File]::WriteAllText($envPath, $envContent, [System.Text.Encoding]::UTF8)
Write-Host ".env written to: $envPath" -ForegroundColor Green

# ---- Install npm packages ----
Write-Host ""
Write-Host "Installing npm packages in backend..." -ForegroundColor Cyan
Set-Location $backendDir
npm install
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAILED: npm install failed." -ForegroundColor Red
    exit 1
}
Write-Host "npm packages installed!" -ForegroundColor Green

# ---- Run migrations ----
Write-Host ""
Write-Host "Running database migrations..." -ForegroundColor Cyan
node migrate.js
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAILED: Migration failed." -ForegroundColor Red
    exit 1
}
Write-Host "All migrations applied!" -ForegroundColor Green

# ---- Seed default data ----
Write-Host ""
Write-Host "Seeding default data..." -ForegroundColor Cyan
& $psql -U $PG_USER -h $PG_HOST -p $PG_PORT -d $DB_NAME -f "seed.sql"
Write-Host "Seed data inserted!" -ForegroundColor Green

# ---- Done ----
Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  DATABASE SETUP COMPLETE" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  Database : $DB_NAME"
Write-Host "  Host     : $PG_HOST`:$PG_PORT"
Write-Host "  User     : $PG_USER"
Write-Host ""
Write-Host "  Default login credentials (password: password123):"
Write-Host "  Admin    : admin@nxtpeople.com"
Write-Host "  Manager  : sarah@nxtpeople.com"
Write-Host "  Employee : michael@nxtpeople.com"
Write-Host ""
Write-Host "  To start the backend:" -ForegroundColor Cyan
Write-Host "  cd backend" -ForegroundColor White
Write-Host "  npm run dev" -ForegroundColor White
Write-Host ""
